-- You can add your own plugins here or in other files in this directory!
--  I promise not to create any merge conflicts in this directory :)
--
-- See the kickstart.nvim README for more information
-- 
-- Individual plugin configurations have been moved to separate files:
-- - oil.lua
-- - telescope-file-browser.lua
--
-- Add new plugins here or create separate files for them.
return {}
